#runtime:     python38
runtime:      python27
threadsafe:   yes
api_version:  1

handlers:
- url:        /.*
  script:     main.app

libraries:
- name:       grpcio
  version:    1.0.0
- name:       setuptools
  version:    36.6.0
